### ISSUE TITLE
Add 1000 most common words in Russian

### ISSUE THREAD

**Issue by aadcg** [dakra/speed-type#22]
[russian.txt](https://github.com/parkouss/speed-type/files/4275958/russian.txt)
Hi,

Thank you for developing this extension. 
I'm learning the russian keyboard layout and I was wondering if you could add the file that I'm attaching here.

If I understood correctly, you add these txt files on the web so that they're then downloaded to ~/.emacs.d/speed-type when the user calls `speed-type-top-1000`.

**Comment by texaco** [comment]
![image](https://user-images.githubusercontent.com/1931261/132109253-aa62d7fd-b444-4dec-bd15-ea8fd0d566c4.png)

All what you have to do is:

- Save your file on ~/.emacs.d/speed-type/Russian.txt
- M-x customize-group RET speed-type RET
- Add new entry on Speed Type WordList Urls with Russian as symbol. You can add whatever you like as string since you already have the file on your system.

Enjoy!

**Comment by dakra** [comment]
If there is a good source of top X (10k+?) words for a language I'm happy to add it to the default wordlist-urls.
But I don't think an upload to the issure here is a good/reliable source.
Honestly I'm also not sure if the web.archive.org from uni-leipzig is the best source (https://github.com/dakra/speed-type/blob/3cec9fe34bc2bd83d43c3a69e937e2126031eb9f/speed-type.el#L71-L76) but I think archive.org will be there
for a long time and copyright and everything is clear from the uni-leipzig site.

Closing for now but re-open or even make a PR if you want to add more languages to the default `wordlist-urls`.
